version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: KomakallioPanel/Dockerfile
    restart: always
    env_file:
      - vhost.env
networks:
  default:
    external:
      name: common-network
